Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,41 +1,80 @@
-
 language: php
 
 sudo: false
 
 git:
-    depth: 2
+  depth: 2
 
 cache:
-    directories:
-        - $HOME/.composer/cache
+  directories:
+    - $HOME/.composer/cache
+    - $HOME/.phive
 
-matrix:
-    fast_finish: true
-    allow_failures:
-        - php: nightly
-    include:
-        - php: 7.1
-        - php: 7.2
-        - php: 7.3
-        - php: 7.4
-        - php: nightly
+jobs:
+  fast_finish: true
+  include:
+    - php: 7.4
+    - php: 7.3
+      env: CODE_COVERAGE=true
+    - php: 7.2
+    - php: 7.1
+    - php: nightly
+    - name: "Coding style"
+      php: 7.3
+      install:
+        - phive install
+      script:
+        - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 -- php -l
+        - tools/php-cs-fixer fix --dry-run
+      after-script:
+    - name: "Static analysis"
+      php: 7.3
+      install:
+        - travis_retry composer require --optimize-autoloader phpstan/phpstan
+      script:
+        - vendor/bin/phpstan analyse
+        - vendor/bin/psalm
+      after-script:
+  allow_failures:
+    - php: nightly
 
-before_script:
-    - php --version
-    - travis_retry wget https://scrutinizer-ci.com/ocular.phar
-    - travis_retry composer self-update
-    - if [ "$(phpenv version-name)" == 7.3 ]; then travis_retry composer require phpstan/phpstan; fi
-    - travis_retry composer require php-coveralls/php-coveralls
-    - travis_retry composer install --prefer-dist --no-interaction
-    - composer dump-autoload -o
+before_install:
+  - |
+    # Install phive if not cached
+    if [ ! -r "${HOME}/.phive/phive.phar" ]; then
+        mkdir -p ~/bin
+        travis_retry wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
+        travis_retry wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
+        travis_retry gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=10 --recv-keys 0x9D8A98B29B2D5D79
+        if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
+            echo "Invalid phive signature" 1>&2
+            rm -f "${HOME}/.phive/phive.phar"
+            exit 11
+        fi
+        rm "${HOME}/.phive/phive.phar.asc"
+    fi
+    install --mode=0755 -T "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"
+    export PATH="${HOME}/bin:${PATH}"
+
+install:
+  - composer validate --strict
+  - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
+  - mkdir -p build/logs
+  # Code coverage
+  - |
+    if [ "${CODE_COVERAGE}" == true ]; then
+        travis_retry composer require --no-interaction --prefer-dist --optimize-autoloader php-coveralls/php-coveralls
+        travis_retry phive install
+    fi
 
 script:
-    - mkdir -p build/logs
-    - php vendor/bin/phpunit -c phpunit.xml
-    - if [ "$(phpenv version-name)" == 7.3 ]; then php vendor/bin/phpstan analyse; fi
+  - vendor/bin/phpunit
 
 after_script:
-    - php vendor/bin/php-coveralls -v
-    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
-    - bash <(curl -s https://codecov.io/bash)
+  # Code coverage
+  - |
+    if [ "${CODE_COVERAGE}" == true ]; then
+        vendor/bin/php-coveralls -v
+        tools/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
+        bash <(curl -s "https://codecov.io/bash")
+    fi
